name: crafty_bay
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#----- App Version -----#
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

#----- User Dependencies -----#
dependencies:
  flutter:
    sdk: flutter

#----- Imported Dependencies -----#
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  widget_and_text_animator: ^1.1.5
  pin_code_fields: ^8.0.1
  device_preview: ^1.2.0
  get: ^4.6.6
  http: ^1.2.2
  floating_snackbar: ^1.0.5
  shared_preferences: ^2.3.2
  jwt_decoder: ^2.0.1
  flutter_carousel_widget: ^2.3.0
  cached_network_image: ^3.4.1
  internet_connection_checker: ^1.0.0+1
  lottie: ^3.1.3
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  webview_flutter: ^4.10.0
  selectable_container: ^1.0.7

#----- Dev Dependencies -----#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

#----- Flutter Packages -----#
flutter:
  uses-material-design: true

  #----- App Assets Section -----#
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/lotties/
  # - images/a_dot_ham.jpeg

  #----- App Fonts -----#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
